/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication78.pkgfor.project.cse3104;

/**
 *
 * @author User
 */
public class showtable extends javax.swing.JFrame {

    /**
     * Creates new form showtable
     */
    public showtable() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonbus = new javax.swing.JButton();
        jButtondriver = new javax.swing.JButton();
        jButtonpassenger = new javax.swing.JButton();
        jButtonadmin = new javax.swing.JButton();
        jButtonticet = new javax.swing.JButton();
        jButtonfeedback = new javax.swing.JButton();
        jButtonback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonbus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonbus.setText("BUS");
        jButtonbus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonbusActionPerformed(evt);
            }
        });

        jButtondriver.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtondriver.setText("DRIVER");
        jButtondriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondriverActionPerformed(evt);
            }
        });

        jButtonpassenger.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonpassenger.setText("PASSENGER");
        jButtonpassenger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonpassengerActionPerformed(evt);
            }
        });

        jButtonadmin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonadmin.setText("ADMIN");
        jButtonadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonadminActionPerformed(evt);
            }
        });

        jButtonticet.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonticet.setText("TICKET");
        jButtonticet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonticetActionPerformed(evt);
            }
        });

        jButtonfeedback.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonfeedback.setText("FEEDBACK");
        jButtonfeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonfeedbackActionPerformed(evt);
            }
        });

        jButtonback.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonback.setText("BACK");
        jButtonback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonback, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButtonadmin, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                        .addComponent(jButtonbus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtondriver, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(jButtonticet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonpassenger, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(jButtonfeedback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonpassenger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtondriver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonbus, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonadmin, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(jButtonticet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonfeedback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(jButtonback, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonbackActionPerformed
        // TODO add your handling code here:
        LogIn obj = new LogIn();
        obj.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonbackActionPerformed

    private void jButtonbusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonbusActionPerformed
        // TODO add your handling code here:
        InsertBus obj = new InsertBus();
        obj.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonbusActionPerformed

    private void jButtondriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondriverActionPerformed
        // TODO add your handling code here:
        insertDriver obj = new insertDriver();
        obj.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtondriverActionPerformed

    private void jButtonpassengerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonpassengerActionPerformed
        // TODO add your handling code here:
        InsertPassenger obj = new InsertPassenger();
        obj.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonpassengerActionPerformed

    private void jButtonadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonadminActionPerformed
        // TODO add your handling code here:
        InsertAdmin obj = new InsertAdmin();
        obj.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonadminActionPerformed

    private void jButtonticetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonticetActionPerformed
        // TODO add your handling code here:
        iNSERTTICKET obj = new iNSERTTICKET();
        obj.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonticetActionPerformed

    private void jButtonfeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonfeedbackActionPerformed
        // TODO add your handling code here:
        InsertFeedback obj = new InsertFeedback();
        obj.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonfeedbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(showtable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(showtable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(showtable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(showtable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new showtable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonadmin;
    private javax.swing.JButton jButtonback;
    private javax.swing.JButton jButtonbus;
    private javax.swing.JButton jButtondriver;
    private javax.swing.JButton jButtonfeedback;
    private javax.swing.JButton jButtonpassenger;
    private javax.swing.JButton jButtonticet;
    // End of variables declaration//GEN-END:variables
}
